### ISSUE TITLE
caps.Lines and caps.Columns wrong values

### ISSUE THREAD

**Issue by samarasteph** [arp242/termfo#1]
With this code:

```
import "zgo.at/termfo"

term_name, exist := os.LookupEnv("TERM")
if !exist || len(term_name) == 0 {
    panic("TERM env not found")
}

term, _ = termfo.New(term_name)
lines := term.Numbers[caps.Lines]
cols := term.Numbers[caps.Columns]

// ==> 'lines' and 'cols' are wrong number

```
I got cols == 80 and lines == 24  instead of right values ${LINES}==19 ${COLUMNS}==200
![Screenshot_20211101_124930](https://user-images.githubusercontent.com/49674088/139667548-24be3207-b4ea-4c9f-967c-c47a838448c6.png)

**Comment by arp242** [comment]
You can't really get the size of a terminal via terminfo; it's just a key/value database with some parameters really. In the old days when terminals were actual physical machines it made sense to "hard-code" them in there, but not with resizeable terminal emulators.

You'll need to use a ioctl to get the terminal size, via the syscall package or golang.org/x/term, which has GetSize() that should work on most (all?) platforms. I avoided doing it here as x/term brings in x/sys, which is a fairly large dependency.

I mostly just want this to load terminfo files without too much extra stuff. I might write a different package based on this which does all of that.

There's some code in cmd/termfo/internal for the demo, but that'll likely only work on Linux (and maybe also some other Unix-y?) systems; not sure about macOS or Windows: https://github.com/arp242/termfo/blob/master/cmd/termfo/internal/term/term.go

**Comment by samarasteph** [comment]
Hi @arp242 ,
thanks for explanations and link
I'll use workaround with x/term.GetSize() or ioctl call (Linux only targeted platform)
